version: "3.7"

services:
    mssql:
        image: microsoft/mssql-server-linux
        container_name: mssql
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: P4ssW0rd!
        networks:
            - network
        ports:
            - 1433:1433
        volumes:
            - mssql:/var/opt/mssql
networks:
    network:
volumes:
    mssql:
        driver: local
